ARG VERSION
FROM debian:buster-20210208-slim

LABEL maintainer="Navio.Online hello@navio.online" \
  org.label-schema.name="Navio.Online Drone Base" \
  org.label-schema.vendor="Navio.Online Team" \
  org.label-schema.schema-version="1.0.0"
